#DATABASE
spring.datasource:
  url: jdbc:mysql://localhost:3306/bus_booking?useSSL=true
  username: booking_user
  password: user123

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true

#FLYWAY
spring.flyway:
  url: jdbc:mysql://localhost:3306?useSSL=true
  user: booking_user
  password: user123
  schemas: bus_booking

#SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
#SECURITY
jwt:
  token:
    secret-key: bus123booking
    expire-length: 900000

